spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: admin
logging:
  level:
    com:
      ibms:
        demo:
          mapper: DEBUG

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ibms.demo.mapper
server:
  port: 81